### ISSUE TITLE
`java.lang.StackOverflowError` when adding `initializeSlf4jBridge` in my project

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-logging#318]
Here's how I initialize my logging layer:

```scala
  val logLayerLive: ULayer[Logging] =
    Slf4jLogger.make((context, message) => "[correlation-id = %s] %s".format(context(correlationId), message))
```

When I launch my app with this configuration, the project start without any issue.

When I add `>>> initializeSlf4jBridge`, then the service generate a `` when booting:

```scala
  val logLayerLive: ULayer[Logging] =
    Slf4jLogger.make((context, message) => "[correlation-id = %s] %s".format(context(correlationId), message)) >>> initializeSlf4jBridge
```

Error:
```scala
[IJ]app-embedded[ERROR] java.lang.StackOverflowError
app-embedded[ERROR] 	at zio.internal.PlatformSpecific$$anon$2.fatal(PlatformSpecific.scala:88)
app-embedded[ERROR] 	at zio.internal.Platform$Proxy.fatal(Platform.scala:110)
app-embedded[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:653)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunWith(Runtime.scala:214)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync(Runtime.scala:83)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:80)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:280)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun(Runtime.scala:58)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun$(Runtime.scala:57)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:280)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLoggerFactory.run(ZioLoggerFactory.scala:19)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.run(ZioLogger.scala:11)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.info(ZioLogger.scala:73)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2(Slf4jLogger.scala:32)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2$adapted(Slf4jLogger.scala:26)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4436)
app-embedded[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:351)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunWith(Runtime.scala:214)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync(Runtime.scala:83)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:80)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:280)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun(Runtime.scala:58)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun$(Runtime.scala:57)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:280)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLoggerFactory.run(ZioLoggerFactory.scala:19)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.run(ZioLogger.scala:11)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.info(ZioLogger.scala:73)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2(Slf4jLogger.scala:32)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2$adapted(Slf4jLogger.scala:26)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4436)
app-embedded[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:351)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunWith(Runtime.scala:214)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync(Runtime.scala:83)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:80)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:280)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun(Runtime.scala:58)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun$(Runtime.scala:57)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:280)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLoggerFactory.run(ZioLoggerFactory.scala:19)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.run(ZioLogger.scala:11)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.info(ZioLogger.scala:73)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2(Slf4jLogger.scala:32)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2$adapted(Slf4jLogger.scala:26)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4436)
app-embedded[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:351)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunWith(Runtime.scala:214)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync(Runtime.scala:83)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:80)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:280)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun(Runtime.scala:58)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun$(Runtime.scala:57)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:280)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLoggerFactory.run(ZioLoggerFactory.scala:19)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.run(ZioLogger.scala:11)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.info(ZioLogger.scala:73)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2(Slf4jLogger.scala:32)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2$adapted(Slf4jLogger.scala:26)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4436)
app-embedded[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:351)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunWith(Runtime.scala:214)
app-embedded **** WARNING ***
app-embedded Catastrophic JVM error encountered. Application not safely interrupted. Resources may be leaked. Check the logs for more details and consider overriding `Platform.reportFatal` to capture context.
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync(Runtime.scala:83)
app-embedded[ERROR] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:80)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:280)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun(Runtime.scala:58)
app-embedded[ERROR] 	at zio.Runtime.unsafeRun$(Runtime.scala:57)
app-embedded[ERROR] 	at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:280)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLoggerFactory.run(ZioLoggerFactory.scala:19)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.run(ZioLogger.scala:11)
app-embedded[ERROR] 	at org.slf4j.impl.ZioLogger.info(ZioLogger.scala:73)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2(Slf4jLogger.scala:32)
app-embedded[ERROR] 	at zio.logging.slf4j.Slf4jLogger$.$anonfun$make$2$adapted(Slf4jLogger.scala:26)
app-embedded[ERROR] 	at zio.ZIO$MapFn.apply(ZIO.scala:4438)
...
```

**Comment by vigoo** [comment]
The `initializeSlf4jBridge` should be used with a zio-logging appender which is not the `Slf4jAppender`. The idea is that with `Slf4jAppender` zio-logging log messages are logged through the SLF4j logger. The `initializeSlf4jBridge` on the other hand sets up SLF4j logging to log through zio-logging. 

You have to have a "real" appender on one of the sides.

**Comment by guizmaii** [comment]
@vigoo Ok thanks! 🙏♥️
