### ISSUE TITLE
Fiber failure when used with Play 2.8

### ISSUE THREAD

**Issue by Cereopsis** [zio/zio-logging#55]
I'm wanting to upgrade some Play apps to use the new ZLayer and have additionally upgraded zio-logging to `0.2.3`. Sbt libraryDependencies are minimal - I'm letting zio-logging pull the zip version it wants to.

I've stripped back to the most basic case here by firing up a play-scala-seed app with the following controller code:

```scala
class HomeController @Inject()(val controllerComponents: ControllerComponents) extends BaseController {

  val layer = (Clock.live ++ Console.live) >>> Logging.console((_, msg) => msg)

  def index() = Action.async { implicit request: Request[AnyContent] =>
    val io = log(LogLevel.Info)("Does this work?") *> UIO(Ok(views.html.index()))
    Runtime.default.unsafeRunToFuture(io.provideLayer(layer))
  }
}
```

If I hit localhost:9000/ a few times it will fairly regularly (but not every request) dump the following trace:

```
2020-03-09T20:13:07.186Z INFO  Does this work?
2020-03-09 20:13:07 ERROR p.api.http.DefaultHttpErrorHandler

! @7f4nk6442 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[InterruptedException: Interrupted by fibers: #120]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:328)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:417)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.InterruptedException: Interrupted by fibers: #120
	at zio.Cause.$anonfun$squashWith$1(Cause.scala:348)
	at scala.Option.orElse(Option.scala:477)
	at zio.Cause.squashWith(Cause.scala:345)
	at zio.Cause.squashWith$(Cause.scala:343)
	at zio.Cause$Internal$Interrupt.squashWith(Cause.scala:648)
	at zio.Cause.squashWithTrace(Cause.scala:370)
	at zio.Cause.squashWithTrace$(Cause.scala:369)
	at zio.Cause$Internal$Interrupt.squashWithTrace(Cause.scala:648)
	at zio.Fiber.$anonfun$toFutureWith$2(Fiber.scala:297)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:383)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: zio.Cause$FiberTrace: Fiber failed.
An interrupt was produced by #120.
No ZIO Trace available.
```

**Comment by Cereopsis** [comment]
Just to confirm, rolling back to `zio 1.0.0-RC17` with `zio-logging 0.2.0` and adjusting the code to the following, we get no errors:

```scala
class HomeController @Inject()(val controllerComponents: ControllerComponents) extends BaseController \
{

  val rts = new	DefaultRuntime{}

  val env = rts.unsafeRun(Logging.console((_, msg) => msg).provide(new Clock.Live with Console.Live))

  def index() = Action.async { implicit request: Request[AnyContent] =>
    val io = log(LogLevel.Info)("Does this work?") *> UIO(Ok(views.html.index()))
    rts.unsafeRunToFuture(io.provide(env))
  }
}
```

**Comment by pshemass** [comment]
@Cereopsis Could you please use `putStrLn` and run the same experiment with `1.0.0-RC18`?

**Comment by Cereopsis** [comment]
@pshemass Good call - fails in exactly the same way. So it seems this really belongs in `zio`. Should I be enabling additional tracing in any way?

```scala
class HomeController @Inject()(val controllerComponents: ControllerComponents) extends BaseController \
{

  val rts = Runtime.unsafeFromLayer(Clock.live ++ Console.live)

  def index() = Action.async { implicit request: Request[AnyContent] =>
    val io = putStrLn("Does this work?") *> UIO(Ok(views.html.index()))
    rts.unsafeRunToFuture(io)
  }
}
```

**Comment by Cereopsis** [comment]
@pshemass Taking it a little bit further after looking at `zio.console` and borrowing the meat of what `putStrLn` actually does, this also works with no errors. Looks like the issue might be in `Fiber`? 

```scala
  final def putStrLn(line: String): UIO[Unit] =
    IO.effectTotal(scala.Console.withOut(scala.Console.out) {
      scala.Console.println(line)
    })

  def index() = Action.async { implicit request: Request[AnyContent] =>
    val io = putStrLn("Does this work?") *> UIO(Ok(views.html.index()))
    Runtime.default.unsafeRunToFuture(io)
  }
```

**Comment by Cereopsis** [comment]
I'll try `zio-logging-slf4j` a bit later - I can't remember quite how I arrived here now but I'm sure I was trying to upgrade a microservice from RC15 -> RC18-1 and was already using slf4j there, so I figure I must have hit the issue then?

**Comment by pshemass** [comment]
@Cereopsis I'm closing this. please open ticket in core
