### ISSUE TITLE
Upgrading break at runtime due to Java Version

### ISSUE THREAD

**Issue by fernanluyano** [zio/zio-logging#888]
Scala Version: 2.12.15
zio version: 2.0.21
zio-logging version: 2.2.2

When I upgrade the the zio-logging version it fails with the following stack trace. There seems to be an underlying dependency that's not compatible with Java 52

```
UnsupportedClassVersionError: zio/internal/MutableQueueFieldsPadding has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:152)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:152)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at zio.internal.PartitionedLinkedQueue.<init>(PartitionedLinkedQueue.scala:26)
	at zio.internal.ZScheduler.<init>(ZScheduler.scala:37)
	at zio.internal.DefaultExecutors.makeDefault(DefaultExecutors.scala:29)
	at zio.RuntimePlatformSpecific.$init$(RuntimePlatformSpecific.scala:26)
	at zio.Runtime$.<init>(Runtime.scala:213)
	at zio.Runtime$.<clinit>(Runtime.scala)
```

**Comment by jivanic-demystdata** [comment]
The ZIO env only supports Java 11+ compatibility.

Java 52 seems to be Java8, which we don't support anymore
See also: https://stackoverflow.com/a/35866015/2431728

**Comment by fernanluyano** [comment]
Where can I find the java versions compatibility of zio?

**Comment by jivanic-demystdata** [comment]
See https://github.com/zio/zio/pull/9224
